// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/admin.proto

package com.rany.service.platform.admin;

public interface GetServiceModeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetServiceModeRequest)
    com.google.protobuf.MessageOrBuilder {
}
