// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

public interface CreateProjectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateProjectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string cluster = 2;</code>
   * @return The cluster.
   */
  java.lang.String getCluster();
  /**
   * <code>string cluster = 2;</code>
   * @return The bytes for cluster.
   */
  com.google.protobuf.ByteString
      getClusterBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string projectSetting = 4;</code>
   * @return The projectSetting.
   */
  java.lang.String getProjectSetting();
  /**
   * <code>string projectSetting = 4;</code>
   * @return The bytes for projectSetting.
   */
  com.google.protobuf.ByteString
      getProjectSettingBytes();
}
