// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

public interface DeleteIndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteIndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index_id = 1;</code>
   */
  int getIndexId();
}
