// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

public interface DeleteIndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteIndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string project = 1;</code>
   * @return The project.
   */
  java.lang.String getProject();
  /**
   * <code>string project = 1;</code>
   * @return The bytes for project.
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>string indexTemplate = 2;</code>
   * @return The indexTemplate.
   */
  java.lang.String getIndexTemplate();
  /**
   * <code>string indexTemplate = 2;</code>
   * @return The bytes for indexTemplate.
   */
  com.google.protobuf.ByteString
      getIndexTemplateBytes();

  /**
   * <code>string indexName = 3;</code>
   * @return The indexName.
   */
  java.lang.String getIndexName();
  /**
   * <code>string indexName = 3;</code>
   * @return The bytes for indexName.
   */
  com.google.protobuf.ByteString
      getIndexNameBytes();
}
