// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

public interface DetachIndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DetachIndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string project = 2;</code>
   * @return The project.
   */
  java.lang.String getProject();
  /**
   * <code>string project = 2;</code>
   * @return The bytes for project.
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>string indexTemplate = 3;</code>
   * @return The indexTemplate.
   */
  java.lang.String getIndexTemplate();
  /**
   * <code>string indexTemplate = 3;</code>
   * @return The bytes for indexTemplate.
   */
  com.google.protobuf.ByteString
      getIndexTemplateBytes();
}
