// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

public interface GetClusterInfoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetClusterInfoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.ClusterInfo cluster = 3;</code>
   * @return Whether the cluster field is set.
   */
  boolean hasCluster();
  /**
   * <code>.ClusterInfo cluster = 3;</code>
   * @return The cluster.
   */
  com.rany.service.platform.meta.ClusterInfo getCluster();
  /**
   * <code>.ClusterInfo cluster = 3;</code>
   */
  com.rany.service.platform.meta.ClusterInfoOrBuilder getClusterOrBuilder();
}
