// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

public interface IndexTemplateInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndexTemplateInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string cluster = 2;</code>
   */
  java.lang.String getCluster();
  /**
   * <code>string cluster = 2;</code>
   */
  com.google.protobuf.ByteString
      getClusterBytes();

  /**
   * <code>string project = 3;</code>
   */
  java.lang.String getProject();
  /**
   * <code>string project = 3;</code>
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>string mapping = 4;</code>
   */
  java.lang.String getMapping();
  /**
   * <code>string mapping = 4;</code>
   */
  com.google.protobuf.ByteString
      getMappingBytes();

  /**
   * <code>string setting = 5;</code>
   */
  java.lang.String getSetting();
  /**
   * <code>string setting = 5;</code>
   */
  com.google.protobuf.ByteString
      getSettingBytes();

  /**
   * <code>repeated string aliases = 6;</code>
   */
  java.util.List<java.lang.String>
      getAliasesList();
  /**
   * <code>repeated string aliases = 6;</code>
   */
  int getAliasesCount();
  /**
   * <code>repeated string aliases = 6;</code>
   */
  java.lang.String getAliases(int index);
  /**
   * <code>repeated string aliases = 6;</code>
   */
  com.google.protobuf.ByteString
      getAliasesBytes(int index);

  /**
   * <code>.AutoIndexRollingPolicy auto_index_rolling_policy = 7;</code>
   */
  int getAutoIndexRollingPolicyValue();
  /**
   * <code>.AutoIndexRollingPolicy auto_index_rolling_policy = 7;</code>
   */
  com.rany.service.platform.meta.AutoIndexRollingPolicy getAutoIndexRollingPolicy();

  /**
   * <code>int32 auto_index_rolling_window = 8;</code>
   */
  int getAutoIndexRollingWindow();

  /**
   * <code>string auto_index_name_prefix = 9;</code>
   */
  java.lang.String getAutoIndexNamePrefix();
  /**
   * <code>string auto_index_name_prefix = 9;</code>
   */
  com.google.protobuf.ByteString
      getAutoIndexNamePrefixBytes();

  /**
   * <pre>
   * number of indices of this index group;
   * </pre>
   *
   * <code>int32 total_index_number = 10;</code>
   */
  int getTotalIndexNumber();

  /**
   * <pre>
   * doc number of all indices of this index group;
   * </pre>
   *
   * <code>int64 total_doc_number = 11;</code>
   */
  long getTotalDocNumber();

  /**
   * <pre>
   * data size of all indices of this index group;
   * </pre>
   *
   * <code>int64 total_data_size = 12;</code>
   */
  long getTotalDataSize();
}
