// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

public interface IndexNameEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndexNameEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string project = 1;</code>
   */
  java.lang.String getProject();
  /**
   * <code>string project = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>string indexTemplate = 2;</code>
   */
  java.lang.String getIndexTemplate();
  /**
   * <code>string indexTemplate = 2;</code>
   */
  com.google.protobuf.ByteString
      getIndexTemplateBytes();

  /**
   * <code>string indexName = 3;</code>
   */
  java.lang.String getIndexName();
  /**
   * <code>string indexName = 3;</code>
   */
  com.google.protobuf.ByteString
      getIndexNameBytes();

  /**
   * <code>string full_name = 4;</code>
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string domain = 5;</code>
   */
  java.lang.String getDomain();
  /**
   * <code>string domain = 5;</code>
   */
  com.google.protobuf.ByteString
      getDomainBytes();

  /**
   * <code>string group = 6;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 6;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();
}
