// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

public interface ListIndexAliasNameReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListIndexAliasNameReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
   */
  java.util.List<com.rany.service.platform.meta.IndexNameEntry> 
      getIndexAliasNamesList();
  /**
   * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
   */
  com.rany.service.platform.meta.IndexNameEntry getIndexAliasNames(int index);
  /**
   * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
   */
  int getIndexAliasNamesCount();
  /**
   * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
   */
  java.util.List<? extends com.rany.service.platform.meta.IndexNameEntryOrBuilder> 
      getIndexAliasNamesOrBuilderList();
  /**
   * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
   */
  com.rany.service.platform.meta.IndexNameEntryOrBuilder getIndexAliasNamesOrBuilder(
      int index);
}
