// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

/**
 * Protobuf type {@code ListClusterDetailsReply}
 */
public final class ListClusterDetailsReply extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ListClusterDetailsReply)
        ListClusterDetailsReplyOrBuilder {
    public static final int CODE_FIELD_NUMBER = 1;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    public static final int CLUSTERS_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:ListClusterDetailsReply)
    private static final com.rany.service.platform.meta.ListClusterDetailsReply DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<ListClusterDetailsReply>
            PARSER = new com.google.protobuf.AbstractParser<ListClusterDetailsReply>() {
        public ListClusterDetailsReply parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new ListClusterDetailsReply(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.rany.service.platform.meta.ListClusterDetailsReply();
    }

    private int bitField0_;
    private int code_;
    private volatile java.lang.Object message_;
    private java.util.List<com.rany.service.platform.meta.ClusterInfo> clusters_;
    private byte memoizedIsInitialized = -1;
    // Use ListClusterDetailsReply.newBuilder() to construct.
    private ListClusterDetailsReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ListClusterDetailsReply() {
        code_ = 0;
        message_ = "";
        clusters_ = java.util.Collections.emptyList();
    }

    private ListClusterDetailsReply(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        code_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        message_ = s;
                        break;
                    }
                    case 26: {
                        if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                            clusters_ = new java.util.ArrayList<com.rany.service.platform.meta.ClusterInfo>();
                            mutable_bitField0_ |= 0x00000004;
                        }
                        clusters_.add(
                                input.readMessage(com.rany.service.platform.meta.ClusterInfo.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                clusters_ = java.util.Collections.unmodifiableList(clusters_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListClusterDetailsReply_descriptor;
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.rany.service.platform.meta.ListClusterDetailsReply prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.rany.service.platform.meta.ListClusterDetailsReply getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<ListClusterDetailsReply> parser() {
        return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListClusterDetailsReply_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.rany.service.platform.meta.ListClusterDetailsReply.class, com.rany.service.platform.meta.ListClusterDetailsReply.Builder.class);
    }

    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
        return code_;
    }

    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            message_ = s;
            return s;
        }
    }

    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
    getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            message_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>repeated .ClusterInfo clusters = 3;</code>
     */
    public java.util.List<com.rany.service.platform.meta.ClusterInfo> getClustersList() {
        return clusters_;
    }

    /**
     * <code>repeated .ClusterInfo clusters = 3;</code>
     */
    public java.util.List<? extends com.rany.service.platform.meta.ClusterInfoOrBuilder>
    getClustersOrBuilderList() {
        return clusters_;
    }

    /**
     * <code>repeated .ClusterInfo clusters = 3;</code>
     */
    public int getClustersCount() {
        return clusters_.size();
    }

    /**
     * <code>repeated .ClusterInfo clusters = 3;</code>
     */
    public com.rany.service.platform.meta.ClusterInfo getClusters(int index) {
        return clusters_.get(index);
    }

    /**
     * <code>repeated .ClusterInfo clusters = 3;</code>
     */
    public com.rany.service.platform.meta.ClusterInfoOrBuilder getClustersOrBuilder(
            int index) {
        return clusters_.get(index);
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (code_ != 0) {
            output.writeInt32(1, code_);
        }
        if (!getMessageBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
        }
        for (int i = 0; i < clusters_.size(); i++) {
            output.writeMessage(3, clusters_.get(i));
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (code_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, code_);
        }
        if (!getMessageBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
        }
        for (int i = 0; i < clusters_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, clusters_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.rany.service.platform.meta.ListClusterDetailsReply)) {
            return super.equals(obj);
        }
        com.rany.service.platform.meta.ListClusterDetailsReply other = (com.rany.service.platform.meta.ListClusterDetailsReply) obj;

        boolean result = true;
        result = result && (getCode()
                == other.getCode());
        result = result && getMessage()
                .equals(other.getMessage());
        result = result && getClustersList()
                .equals(other.getClustersList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        if (getClustersCount() > 0) {
            hash = (37 * hash) + CLUSTERS_FIELD_NUMBER;
            hash = (53 * hash) + getClustersList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListClusterDetailsReply> getParserForType() {
        return PARSER;
    }

    public com.rany.service.platform.meta.ListClusterDetailsReply getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code ListClusterDetailsReply}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:ListClusterDetailsReply)
            com.rany.service.platform.meta.ListClusterDetailsReplyOrBuilder {
        private int bitField0_;
        private int code_;
        private java.lang.Object message_ = "";
        private java.util.List<com.rany.service.platform.meta.ClusterInfo> clusters_ =
                java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.rany.service.platform.meta.ClusterInfo, com.rany.service.platform.meta.ClusterInfo.Builder, com.rany.service.platform.meta.ClusterInfoOrBuilder> clustersBuilder_;

        // Construct using com.rany.service.platform.meta.ListClusterDetailsReply.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListClusterDetailsReply_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListClusterDetailsReply_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.rany.service.platform.meta.ListClusterDetailsReply.class, com.rany.service.platform.meta.ListClusterDetailsReply.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getClustersFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            code_ = 0;

            message_ = "";

            if (clustersBuilder_ == null) {
                clusters_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000004);
            } else {
                clustersBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListClusterDetailsReply_descriptor;
        }

        public com.rany.service.platform.meta.ListClusterDetailsReply getDefaultInstanceForType() {
            return com.rany.service.platform.meta.ListClusterDetailsReply.getDefaultInstance();
        }

        public com.rany.service.platform.meta.ListClusterDetailsReply build() {
            com.rany.service.platform.meta.ListClusterDetailsReply result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.rany.service.platform.meta.ListClusterDetailsReply buildPartial() {
            com.rany.service.platform.meta.ListClusterDetailsReply result = new com.rany.service.platform.meta.ListClusterDetailsReply(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.code_ = code_;
            result.message_ = message_;
            if (clustersBuilder_ == null) {
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    clusters_ = java.util.Collections.unmodifiableList(clusters_);
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.clusters_ = clusters_;
            } else {
                result.clusters_ = clustersBuilder_.build();
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.rany.service.platform.meta.ListClusterDetailsReply) {
                return mergeFrom((com.rany.service.platform.meta.ListClusterDetailsReply) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.rany.service.platform.meta.ListClusterDetailsReply other) {
            if (other == com.rany.service.platform.meta.ListClusterDetailsReply.getDefaultInstance()) return this;
            if (other.getCode() != 0) {
                setCode(other.getCode());
            }
            if (!other.getMessage().isEmpty()) {
                message_ = other.message_;
                onChanged();
            }
            if (clustersBuilder_ == null) {
                if (!other.clusters_.isEmpty()) {
                    if (clusters_.isEmpty()) {
                        clusters_ = other.clusters_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureClustersIsMutable();
                        clusters_.addAll(other.clusters_);
                    }
                    onChanged();
                }
            } else {
                if (!other.clusters_.isEmpty()) {
                    if (clustersBuilder_.isEmpty()) {
                        clustersBuilder_.dispose();
                        clustersBuilder_ = null;
                        clusters_ = other.clusters_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                        clustersBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getClustersFieldBuilder() : null;
                    } else {
                        clustersBuilder_.addAllMessages(other.clusters_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.rany.service.platform.meta.ListClusterDetailsReply parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.rany.service.platform.meta.ListClusterDetailsReply) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>int32 code = 1;</code>
         */
        public int getCode() {
            return code_;
        }

        /**
         * <code>int32 code = 1;</code>
         */
        public Builder setCode(int value) {

            code_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 code = 1;</code>
         */
        public Builder clearCode() {

            code_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>string message = 2;</code>
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                message_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string message = 2;</code>
         */
        public Builder setMessage(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            message_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string message = 2;</code>
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string message = 2;</code>
         */
        public Builder setMessageBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            message_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string message = 2;</code>
         */
        public Builder clearMessage() {

            message_ = getDefaultInstance().getMessage();
            onChanged();
            return this;
        }

        private void ensureClustersIsMutable() {
            if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                clusters_ = new java.util.ArrayList<com.rany.service.platform.meta.ClusterInfo>(clusters_);
                bitField0_ |= 0x00000004;
            }
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public java.util.List<com.rany.service.platform.meta.ClusterInfo> getClustersList() {
            if (clustersBuilder_ == null) {
                return java.util.Collections.unmodifiableList(clusters_);
            } else {
                return clustersBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public int getClustersCount() {
            if (clustersBuilder_ == null) {
                return clusters_.size();
            } else {
                return clustersBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public com.rany.service.platform.meta.ClusterInfo getClusters(int index) {
            if (clustersBuilder_ == null) {
                return clusters_.get(index);
            } else {
                return clustersBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public Builder setClusters(
                int index, com.rany.service.platform.meta.ClusterInfo value) {
            if (clustersBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureClustersIsMutable();
                clusters_.set(index, value);
                onChanged();
            } else {
                clustersBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public Builder setClusters(
                int index, com.rany.service.platform.meta.ClusterInfo.Builder builderForValue) {
            if (clustersBuilder_ == null) {
                ensureClustersIsMutable();
                clusters_.set(index, builderForValue.build());
                onChanged();
            } else {
                clustersBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public Builder addClusters(com.rany.service.platform.meta.ClusterInfo value) {
            if (clustersBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureClustersIsMutable();
                clusters_.add(value);
                onChanged();
            } else {
                clustersBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public Builder addClusters(
                int index, com.rany.service.platform.meta.ClusterInfo value) {
            if (clustersBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureClustersIsMutable();
                clusters_.add(index, value);
                onChanged();
            } else {
                clustersBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public Builder addClusters(
                com.rany.service.platform.meta.ClusterInfo.Builder builderForValue) {
            if (clustersBuilder_ == null) {
                ensureClustersIsMutable();
                clusters_.add(builderForValue.build());
                onChanged();
            } else {
                clustersBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public Builder addClusters(
                int index, com.rany.service.platform.meta.ClusterInfo.Builder builderForValue) {
            if (clustersBuilder_ == null) {
                ensureClustersIsMutable();
                clusters_.add(index, builderForValue.build());
                onChanged();
            } else {
                clustersBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public Builder addAllClusters(
                java.lang.Iterable<? extends com.rany.service.platform.meta.ClusterInfo> values) {
            if (clustersBuilder_ == null) {
                ensureClustersIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, clusters_);
                onChanged();
            } else {
                clustersBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public Builder clearClusters() {
            if (clustersBuilder_ == null) {
                clusters_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
            } else {
                clustersBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public Builder removeClusters(int index) {
            if (clustersBuilder_ == null) {
                ensureClustersIsMutable();
                clusters_.remove(index);
                onChanged();
            } else {
                clustersBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public com.rany.service.platform.meta.ClusterInfo.Builder getClustersBuilder(
                int index) {
            return getClustersFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public com.rany.service.platform.meta.ClusterInfoOrBuilder getClustersOrBuilder(
                int index) {
            if (clustersBuilder_ == null) {
                return clusters_.get(index);
            } else {
                return clustersBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public java.util.List<? extends com.rany.service.platform.meta.ClusterInfoOrBuilder>
        getClustersOrBuilderList() {
            if (clustersBuilder_ != null) {
                return clustersBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(clusters_);
            }
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public com.rany.service.platform.meta.ClusterInfo.Builder addClustersBuilder() {
            return getClustersFieldBuilder().addBuilder(
                    com.rany.service.platform.meta.ClusterInfo.getDefaultInstance());
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public com.rany.service.platform.meta.ClusterInfo.Builder addClustersBuilder(
                int index) {
            return getClustersFieldBuilder().addBuilder(
                    index, com.rany.service.platform.meta.ClusterInfo.getDefaultInstance());
        }

        /**
         * <code>repeated .ClusterInfo clusters = 3;</code>
         */
        public java.util.List<com.rany.service.platform.meta.ClusterInfo.Builder>
        getClustersBuilderList() {
            return getClustersFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.rany.service.platform.meta.ClusterInfo, com.rany.service.platform.meta.ClusterInfo.Builder, com.rany.service.platform.meta.ClusterInfoOrBuilder>
        getClustersFieldBuilder() {
            if (clustersBuilder_ == null) {
                clustersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        com.rany.service.platform.meta.ClusterInfo, com.rany.service.platform.meta.ClusterInfo.Builder, com.rany.service.platform.meta.ClusterInfoOrBuilder>(
                        clusters_,
                        ((bitField0_ & 0x00000004) == 0x00000004),
                        getParentForChildren(),
                        isClean());
                clusters_ = null;
            }
            return clustersBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ListClusterDetailsReply)
    }

}

