// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

/**
 * Protobuf type {@code ListIndexNameReply}
 */
public  final class ListIndexNameReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListIndexNameReply)
    ListIndexNameReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListIndexNameReply.newBuilder() to construct.
  private ListIndexNameReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListIndexNameReply() {
    code_ = 0;
    message_ = "";
    indexNames_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListIndexNameReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              indexNames_ = new java.util.ArrayList<com.rany.service.platform.meta.IndexNameEntry>();
              mutable_bitField0_ |= 0x00000004;
            }
            indexNames_.add(
                input.readMessage(com.rany.service.platform.meta.IndexNameEntry.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        indexNames_ = java.util.Collections.unmodifiableList(indexNames_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListIndexNameReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListIndexNameReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rany.service.platform.meta.ListIndexNameReply.class, com.rany.service.platform.meta.ListIndexNameReply.Builder.class);
  }

  private int bitField0_;
  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>int32 code = 1;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDEXNAMES_FIELD_NUMBER = 3;
  private java.util.List<com.rany.service.platform.meta.IndexNameEntry> indexNames_;
  /**
   * <code>repeated .IndexNameEntry indexNames = 3;</code>
   */
  public java.util.List<com.rany.service.platform.meta.IndexNameEntry> getIndexNamesList() {
    return indexNames_;
  }
  /**
   * <code>repeated .IndexNameEntry indexNames = 3;</code>
   */
  public java.util.List<? extends com.rany.service.platform.meta.IndexNameEntryOrBuilder> 
      getIndexNamesOrBuilderList() {
    return indexNames_;
  }
  /**
   * <code>repeated .IndexNameEntry indexNames = 3;</code>
   */
  public int getIndexNamesCount() {
    return indexNames_.size();
  }
  /**
   * <code>repeated .IndexNameEntry indexNames = 3;</code>
   */
  public com.rany.service.platform.meta.IndexNameEntry getIndexNames(int index) {
    return indexNames_.get(index);
  }
  /**
   * <code>repeated .IndexNameEntry indexNames = 3;</code>
   */
  public com.rany.service.platform.meta.IndexNameEntryOrBuilder getIndexNamesOrBuilder(
      int index) {
    return indexNames_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < indexNames_.size(); i++) {
      output.writeMessage(3, indexNames_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    for (int i = 0; i < indexNames_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, indexNames_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rany.service.platform.meta.ListIndexNameReply)) {
      return super.equals(obj);
    }
    com.rany.service.platform.meta.ListIndexNameReply other = (com.rany.service.platform.meta.ListIndexNameReply) obj;

    boolean result = true;
    result = result && (getCode()
        == other.getCode());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getIndexNamesList()
        .equals(other.getIndexNamesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getIndexNamesCount() > 0) {
      hash = (37 * hash) + INDEXNAMES_FIELD_NUMBER;
      hash = (53 * hash) + getIndexNamesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rany.service.platform.meta.ListIndexNameReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rany.service.platform.meta.ListIndexNameReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rany.service.platform.meta.ListIndexNameReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListIndexNameReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListIndexNameReply)
      com.rany.service.platform.meta.ListIndexNameReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListIndexNameReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListIndexNameReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rany.service.platform.meta.ListIndexNameReply.class, com.rany.service.platform.meta.ListIndexNameReply.Builder.class);
    }

    // Construct using com.rany.service.platform.meta.ListIndexNameReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIndexNamesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      code_ = 0;

      message_ = "";

      if (indexNamesBuilder_ == null) {
        indexNames_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        indexNamesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListIndexNameReply_descriptor;
    }

    public com.rany.service.platform.meta.ListIndexNameReply getDefaultInstanceForType() {
      return com.rany.service.platform.meta.ListIndexNameReply.getDefaultInstance();
    }

    public com.rany.service.platform.meta.ListIndexNameReply build() {
      com.rany.service.platform.meta.ListIndexNameReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.rany.service.platform.meta.ListIndexNameReply buildPartial() {
      com.rany.service.platform.meta.ListIndexNameReply result = new com.rany.service.platform.meta.ListIndexNameReply(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.code_ = code_;
      result.message_ = message_;
      if (indexNamesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          indexNames_ = java.util.Collections.unmodifiableList(indexNames_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.indexNames_ = indexNames_;
      } else {
        result.indexNames_ = indexNamesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rany.service.platform.meta.ListIndexNameReply) {
        return mergeFrom((com.rany.service.platform.meta.ListIndexNameReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rany.service.platform.meta.ListIndexNameReply other) {
      if (other == com.rany.service.platform.meta.ListIndexNameReply.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (indexNamesBuilder_ == null) {
        if (!other.indexNames_.isEmpty()) {
          if (indexNames_.isEmpty()) {
            indexNames_ = other.indexNames_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureIndexNamesIsMutable();
            indexNames_.addAll(other.indexNames_);
          }
          onChanged();
        }
      } else {
        if (!other.indexNames_.isEmpty()) {
          if (indexNamesBuilder_.isEmpty()) {
            indexNamesBuilder_.dispose();
            indexNamesBuilder_ = null;
            indexNames_ = other.indexNames_;
            bitField0_ = (bitField0_ & ~0x00000004);
            indexNamesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIndexNamesFieldBuilder() : null;
          } else {
            indexNamesBuilder_.addAllMessages(other.indexNames_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.rany.service.platform.meta.ListIndexNameReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.rany.service.platform.meta.ListIndexNameReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int code_ ;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.rany.service.platform.meta.IndexNameEntry> indexNames_ =
      java.util.Collections.emptyList();
    private void ensureIndexNamesIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        indexNames_ = new java.util.ArrayList<com.rany.service.platform.meta.IndexNameEntry>(indexNames_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.rany.service.platform.meta.IndexNameEntry, com.rany.service.platform.meta.IndexNameEntry.Builder, com.rany.service.platform.meta.IndexNameEntryOrBuilder> indexNamesBuilder_;

    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public java.util.List<com.rany.service.platform.meta.IndexNameEntry> getIndexNamesList() {
      if (indexNamesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(indexNames_);
      } else {
        return indexNamesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public int getIndexNamesCount() {
      if (indexNamesBuilder_ == null) {
        return indexNames_.size();
      } else {
        return indexNamesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public com.rany.service.platform.meta.IndexNameEntry getIndexNames(int index) {
      if (indexNamesBuilder_ == null) {
        return indexNames_.get(index);
      } else {
        return indexNamesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public Builder setIndexNames(
        int index, com.rany.service.platform.meta.IndexNameEntry value) {
      if (indexNamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexNamesIsMutable();
        indexNames_.set(index, value);
        onChanged();
      } else {
        indexNamesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public Builder setIndexNames(
        int index, com.rany.service.platform.meta.IndexNameEntry.Builder builderForValue) {
      if (indexNamesBuilder_ == null) {
        ensureIndexNamesIsMutable();
        indexNames_.set(index, builderForValue.build());
        onChanged();
      } else {
        indexNamesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public Builder addIndexNames(com.rany.service.platform.meta.IndexNameEntry value) {
      if (indexNamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexNamesIsMutable();
        indexNames_.add(value);
        onChanged();
      } else {
        indexNamesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public Builder addIndexNames(
        int index, com.rany.service.platform.meta.IndexNameEntry value) {
      if (indexNamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexNamesIsMutable();
        indexNames_.add(index, value);
        onChanged();
      } else {
        indexNamesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public Builder addIndexNames(
        com.rany.service.platform.meta.IndexNameEntry.Builder builderForValue) {
      if (indexNamesBuilder_ == null) {
        ensureIndexNamesIsMutable();
        indexNames_.add(builderForValue.build());
        onChanged();
      } else {
        indexNamesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public Builder addIndexNames(
        int index, com.rany.service.platform.meta.IndexNameEntry.Builder builderForValue) {
      if (indexNamesBuilder_ == null) {
        ensureIndexNamesIsMutable();
        indexNames_.add(index, builderForValue.build());
        onChanged();
      } else {
        indexNamesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public Builder addAllIndexNames(
        java.lang.Iterable<? extends com.rany.service.platform.meta.IndexNameEntry> values) {
      if (indexNamesBuilder_ == null) {
        ensureIndexNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, indexNames_);
        onChanged();
      } else {
        indexNamesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public Builder clearIndexNames() {
      if (indexNamesBuilder_ == null) {
        indexNames_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        indexNamesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public Builder removeIndexNames(int index) {
      if (indexNamesBuilder_ == null) {
        ensureIndexNamesIsMutable();
        indexNames_.remove(index);
        onChanged();
      } else {
        indexNamesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public com.rany.service.platform.meta.IndexNameEntry.Builder getIndexNamesBuilder(
        int index) {
      return getIndexNamesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public com.rany.service.platform.meta.IndexNameEntryOrBuilder getIndexNamesOrBuilder(
        int index) {
      if (indexNamesBuilder_ == null) {
        return indexNames_.get(index);  } else {
        return indexNamesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public java.util.List<? extends com.rany.service.platform.meta.IndexNameEntryOrBuilder> 
         getIndexNamesOrBuilderList() {
      if (indexNamesBuilder_ != null) {
        return indexNamesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(indexNames_);
      }
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public com.rany.service.platform.meta.IndexNameEntry.Builder addIndexNamesBuilder() {
      return getIndexNamesFieldBuilder().addBuilder(
          com.rany.service.platform.meta.IndexNameEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public com.rany.service.platform.meta.IndexNameEntry.Builder addIndexNamesBuilder(
        int index) {
      return getIndexNamesFieldBuilder().addBuilder(
          index, com.rany.service.platform.meta.IndexNameEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .IndexNameEntry indexNames = 3;</code>
     */
    public java.util.List<com.rany.service.platform.meta.IndexNameEntry.Builder> 
         getIndexNamesBuilderList() {
      return getIndexNamesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.rany.service.platform.meta.IndexNameEntry, com.rany.service.platform.meta.IndexNameEntry.Builder, com.rany.service.platform.meta.IndexNameEntryOrBuilder> 
        getIndexNamesFieldBuilder() {
      if (indexNamesBuilder_ == null) {
        indexNamesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.rany.service.platform.meta.IndexNameEntry, com.rany.service.platform.meta.IndexNameEntry.Builder, com.rany.service.platform.meta.IndexNameEntryOrBuilder>(
                indexNames_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        indexNames_ = null;
      }
      return indexNamesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListIndexNameReply)
  }

  // @@protoc_insertion_point(class_scope:ListIndexNameReply)
  private static final com.rany.service.platform.meta.ListIndexNameReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rany.service.platform.meta.ListIndexNameReply();
  }

  public static com.rany.service.platform.meta.ListIndexNameReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListIndexNameReply>
      PARSER = new com.google.protobuf.AbstractParser<ListIndexNameReply>() {
    public ListIndexNameReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListIndexNameReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListIndexNameReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListIndexNameReply> getParserForType() {
    return PARSER;
  }

  public com.rany.service.platform.meta.ListIndexNameReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

