// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

/**
 * Protobuf type {@code ListIndexAliasNameReply}
 */
public final class ListIndexAliasNameReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListIndexAliasNameReply)
    ListIndexAliasNameReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListIndexAliasNameReply.newBuilder() to construct.
  private ListIndexAliasNameReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListIndexAliasNameReply() {
    message_ = "";
    indexAliasNames_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListIndexAliasNameReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListIndexAliasNameReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              indexAliasNames_ = new java.util.ArrayList<com.rany.service.platform.meta.IndexNameEntry>();
              mutable_bitField0_ |= 0x00000001;
            }
            indexAliasNames_.add(
                input.readMessage(com.rany.service.platform.meta.IndexNameEntry.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        indexAliasNames_ = java.util.Collections.unmodifiableList(indexAliasNames_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListIndexAliasNameReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListIndexAliasNameReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rany.service.platform.meta.ListIndexAliasNameReply.class, com.rany.service.platform.meta.ListIndexAliasNameReply.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDEXALIASNAMES_FIELD_NUMBER = 3;
  private java.util.List<com.rany.service.platform.meta.IndexNameEntry> indexAliasNames_;
  /**
   * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.rany.service.platform.meta.IndexNameEntry> getIndexAliasNamesList() {
    return indexAliasNames_;
  }
  /**
   * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.rany.service.platform.meta.IndexNameEntryOrBuilder> 
      getIndexAliasNamesOrBuilderList() {
    return indexAliasNames_;
  }
  /**
   * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
   */
  @java.lang.Override
  public int getIndexAliasNamesCount() {
    return indexAliasNames_.size();
  }
  /**
   * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
   */
  @java.lang.Override
  public com.rany.service.platform.meta.IndexNameEntry getIndexAliasNames(int index) {
    return indexAliasNames_.get(index);
  }
  /**
   * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
   */
  @java.lang.Override
  public com.rany.service.platform.meta.IndexNameEntryOrBuilder getIndexAliasNamesOrBuilder(
      int index) {
    return indexAliasNames_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < indexAliasNames_.size(); i++) {
      output.writeMessage(3, indexAliasNames_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    for (int i = 0; i < indexAliasNames_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, indexAliasNames_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rany.service.platform.meta.ListIndexAliasNameReply)) {
      return super.equals(obj);
    }
    com.rany.service.platform.meta.ListIndexAliasNameReply other = (com.rany.service.platform.meta.ListIndexAliasNameReply) obj;

    if (getCode()
        != other.getCode()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getIndexAliasNamesList()
        .equals(other.getIndexAliasNamesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getIndexAliasNamesCount() > 0) {
      hash = (37 * hash) + INDEXALIASNAMES_FIELD_NUMBER;
      hash = (53 * hash) + getIndexAliasNamesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rany.service.platform.meta.ListIndexAliasNameReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rany.service.platform.meta.ListIndexAliasNameReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListIndexAliasNameReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListIndexAliasNameReply)
      com.rany.service.platform.meta.ListIndexAliasNameReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListIndexAliasNameReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListIndexAliasNameReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rany.service.platform.meta.ListIndexAliasNameReply.class, com.rany.service.platform.meta.ListIndexAliasNameReply.Builder.class);
    }

    // Construct using com.rany.service.platform.meta.ListIndexAliasNameReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIndexAliasNamesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      code_ = 0;

      message_ = "";

      if (indexAliasNamesBuilder_ == null) {
        indexAliasNames_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        indexAliasNamesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_ListIndexAliasNameReply_descriptor;
    }

    @java.lang.Override
    public com.rany.service.platform.meta.ListIndexAliasNameReply getDefaultInstanceForType() {
      return com.rany.service.platform.meta.ListIndexAliasNameReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.rany.service.platform.meta.ListIndexAliasNameReply build() {
      com.rany.service.platform.meta.ListIndexAliasNameReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rany.service.platform.meta.ListIndexAliasNameReply buildPartial() {
      com.rany.service.platform.meta.ListIndexAliasNameReply result = new com.rany.service.platform.meta.ListIndexAliasNameReply(this);
      int from_bitField0_ = bitField0_;
      result.code_ = code_;
      result.message_ = message_;
      if (indexAliasNamesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          indexAliasNames_ = java.util.Collections.unmodifiableList(indexAliasNames_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.indexAliasNames_ = indexAliasNames_;
      } else {
        result.indexAliasNames_ = indexAliasNamesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rany.service.platform.meta.ListIndexAliasNameReply) {
        return mergeFrom((com.rany.service.platform.meta.ListIndexAliasNameReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rany.service.platform.meta.ListIndexAliasNameReply other) {
      if (other == com.rany.service.platform.meta.ListIndexAliasNameReply.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (indexAliasNamesBuilder_ == null) {
        if (!other.indexAliasNames_.isEmpty()) {
          if (indexAliasNames_.isEmpty()) {
            indexAliasNames_ = other.indexAliasNames_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIndexAliasNamesIsMutable();
            indexAliasNames_.addAll(other.indexAliasNames_);
          }
          onChanged();
        }
      } else {
        if (!other.indexAliasNames_.isEmpty()) {
          if (indexAliasNamesBuilder_.isEmpty()) {
            indexAliasNamesBuilder_.dispose();
            indexAliasNamesBuilder_ = null;
            indexAliasNames_ = other.indexAliasNames_;
            bitField0_ = (bitField0_ & ~0x00000001);
            indexAliasNamesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIndexAliasNamesFieldBuilder() : null;
          } else {
            indexAliasNamesBuilder_.addAllMessages(other.indexAliasNames_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.rany.service.platform.meta.ListIndexAliasNameReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.rany.service.platform.meta.ListIndexAliasNameReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int code_ ;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.rany.service.platform.meta.IndexNameEntry> indexAliasNames_ =
      java.util.Collections.emptyList();
    private void ensureIndexAliasNamesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        indexAliasNames_ = new java.util.ArrayList<com.rany.service.platform.meta.IndexNameEntry>(indexAliasNames_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.rany.service.platform.meta.IndexNameEntry, com.rany.service.platform.meta.IndexNameEntry.Builder, com.rany.service.platform.meta.IndexNameEntryOrBuilder> indexAliasNamesBuilder_;

    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public java.util.List<com.rany.service.platform.meta.IndexNameEntry> getIndexAliasNamesList() {
      if (indexAliasNamesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(indexAliasNames_);
      } else {
        return indexAliasNamesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public int getIndexAliasNamesCount() {
      if (indexAliasNamesBuilder_ == null) {
        return indexAliasNames_.size();
      } else {
        return indexAliasNamesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public com.rany.service.platform.meta.IndexNameEntry getIndexAliasNames(int index) {
      if (indexAliasNamesBuilder_ == null) {
        return indexAliasNames_.get(index);
      } else {
        return indexAliasNamesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public Builder setIndexAliasNames(
        int index, com.rany.service.platform.meta.IndexNameEntry value) {
      if (indexAliasNamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexAliasNamesIsMutable();
        indexAliasNames_.set(index, value);
        onChanged();
      } else {
        indexAliasNamesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public Builder setIndexAliasNames(
        int index, com.rany.service.platform.meta.IndexNameEntry.Builder builderForValue) {
      if (indexAliasNamesBuilder_ == null) {
        ensureIndexAliasNamesIsMutable();
        indexAliasNames_.set(index, builderForValue.build());
        onChanged();
      } else {
        indexAliasNamesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public Builder addIndexAliasNames(com.rany.service.platform.meta.IndexNameEntry value) {
      if (indexAliasNamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexAliasNamesIsMutable();
        indexAliasNames_.add(value);
        onChanged();
      } else {
        indexAliasNamesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public Builder addIndexAliasNames(
        int index, com.rany.service.platform.meta.IndexNameEntry value) {
      if (indexAliasNamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIndexAliasNamesIsMutable();
        indexAliasNames_.add(index, value);
        onChanged();
      } else {
        indexAliasNamesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public Builder addIndexAliasNames(
        com.rany.service.platform.meta.IndexNameEntry.Builder builderForValue) {
      if (indexAliasNamesBuilder_ == null) {
        ensureIndexAliasNamesIsMutable();
        indexAliasNames_.add(builderForValue.build());
        onChanged();
      } else {
        indexAliasNamesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public Builder addIndexAliasNames(
        int index, com.rany.service.platform.meta.IndexNameEntry.Builder builderForValue) {
      if (indexAliasNamesBuilder_ == null) {
        ensureIndexAliasNamesIsMutable();
        indexAliasNames_.add(index, builderForValue.build());
        onChanged();
      } else {
        indexAliasNamesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public Builder addAllIndexAliasNames(
        java.lang.Iterable<? extends com.rany.service.platform.meta.IndexNameEntry> values) {
      if (indexAliasNamesBuilder_ == null) {
        ensureIndexAliasNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, indexAliasNames_);
        onChanged();
      } else {
        indexAliasNamesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public Builder clearIndexAliasNames() {
      if (indexAliasNamesBuilder_ == null) {
        indexAliasNames_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        indexAliasNamesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public Builder removeIndexAliasNames(int index) {
      if (indexAliasNamesBuilder_ == null) {
        ensureIndexAliasNamesIsMutable();
        indexAliasNames_.remove(index);
        onChanged();
      } else {
        indexAliasNamesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public com.rany.service.platform.meta.IndexNameEntry.Builder getIndexAliasNamesBuilder(
        int index) {
      return getIndexAliasNamesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public com.rany.service.platform.meta.IndexNameEntryOrBuilder getIndexAliasNamesOrBuilder(
        int index) {
      if (indexAliasNamesBuilder_ == null) {
        return indexAliasNames_.get(index);  } else {
        return indexAliasNamesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public java.util.List<? extends com.rany.service.platform.meta.IndexNameEntryOrBuilder> 
         getIndexAliasNamesOrBuilderList() {
      if (indexAliasNamesBuilder_ != null) {
        return indexAliasNamesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(indexAliasNames_);
      }
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public com.rany.service.platform.meta.IndexNameEntry.Builder addIndexAliasNamesBuilder() {
      return getIndexAliasNamesFieldBuilder().addBuilder(
          com.rany.service.platform.meta.IndexNameEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public com.rany.service.platform.meta.IndexNameEntry.Builder addIndexAliasNamesBuilder(
        int index) {
      return getIndexAliasNamesFieldBuilder().addBuilder(
          index, com.rany.service.platform.meta.IndexNameEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .IndexNameEntry indexAliasNames = 3;</code>
     */
    public java.util.List<com.rany.service.platform.meta.IndexNameEntry.Builder> 
         getIndexAliasNamesBuilderList() {
      return getIndexAliasNamesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.rany.service.platform.meta.IndexNameEntry, com.rany.service.platform.meta.IndexNameEntry.Builder, com.rany.service.platform.meta.IndexNameEntryOrBuilder> 
        getIndexAliasNamesFieldBuilder() {
      if (indexAliasNamesBuilder_ == null) {
        indexAliasNamesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.rany.service.platform.meta.IndexNameEntry, com.rany.service.platform.meta.IndexNameEntry.Builder, com.rany.service.platform.meta.IndexNameEntryOrBuilder>(
                indexAliasNames_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        indexAliasNames_ = null;
      }
      return indexAliasNamesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListIndexAliasNameReply)
  }

  // @@protoc_insertion_point(class_scope:ListIndexAliasNameReply)
  private static final com.rany.service.platform.meta.ListIndexAliasNameReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rany.service.platform.meta.ListIndexAliasNameReply();
  }

  public static com.rany.service.platform.meta.ListIndexAliasNameReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListIndexAliasNameReply>
      PARSER = new com.google.protobuf.AbstractParser<ListIndexAliasNameReply>() {
    @java.lang.Override
    public ListIndexAliasNameReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListIndexAliasNameReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListIndexAliasNameReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListIndexAliasNameReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rany.service.platform.meta.ListIndexAliasNameReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

