// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

/**
 * Protobuf type {@code NodeInfo}
 */
public final class NodeInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:NodeInfo)
        NodeInfoOrBuilder {
    public static final int ID_FIELD_NUMBER = 1;
    public static final int NAME_FIELD_NUMBER = 2;
    public static final int IP_ADDRESS_FIELD_NUMBER = 3;
    public static final int IS_MASTER_FIELD_NUMBER = 4;
    public static final int CPU_PERCENT_FIELD_NUMBER = 5;
    public static final int RAM_MAX_FIELD_NUMBER = 6;
    public static final int RAM_CURRENT_FIELD_NUMBER = 7;
    public static final int HEAP_MAX_FIELD_NUMBER = 8;
    public static final int HEAP_CURRENT_FIELD_NUMBER = 9;
    public static final int DISK_AVAIL_FIELD_NUMBER = 10;
    public static final int DISK_PERCENT_FIELD_NUMBER = 11;
    public static final int GROUP_FIELD_NUMBER = 12;
    public static final int TAG_FIELD_NUMBER = 13;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:NodeInfo)
    private static final com.rany.service.platform.meta.NodeInfo DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<NodeInfo>
            PARSER = new com.google.protobuf.AbstractParser<NodeInfo>() {
        public NodeInfo parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new NodeInfo(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.rany.service.platform.meta.NodeInfo();
    }

    private int id_;
    private volatile java.lang.Object name_;
    private volatile java.lang.Object ipAddress_;
    private boolean isMaster_;
    private double cpuPercent_;
    private volatile java.lang.Object ramMax_;
    private volatile java.lang.Object ramCurrent_;
    private volatile java.lang.Object heapMax_;
    private volatile java.lang.Object heapCurrent_;
    private volatile java.lang.Object diskAvail_;
    private double diskPercent_;
    private volatile java.lang.Object group_;
    private volatile java.lang.Object tag_;
    private byte memoizedIsInitialized = -1;

    // Use NodeInfo.newBuilder() to construct.
    private NodeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private NodeInfo() {
        id_ = 0;
        name_ = "";
        ipAddress_ = "";
        isMaster_ = false;
        cpuPercent_ = 0D;
        ramMax_ = "";
        ramCurrent_ = "";
        heapMax_ = "";
        heapCurrent_ = "";
        diskAvail_ = "";
        diskPercent_ = 0D;
        group_ = "";
        tag_ = "";
    }
    private NodeInfo(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        id_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        name_ = s;
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();

                        ipAddress_ = s;
                        break;
                    }
                    case 32: {

                        isMaster_ = input.readBool();
                        break;
                    }
                    case 41: {

                        cpuPercent_ = input.readDouble();
                        break;
                    }
                    case 50: {
                        java.lang.String s = input.readStringRequireUtf8();

                        ramMax_ = s;
                        break;
                    }
                    case 58: {
                        java.lang.String s = input.readStringRequireUtf8();

                        ramCurrent_ = s;
                        break;
                    }
                    case 66: {
                        java.lang.String s = input.readStringRequireUtf8();

                        heapMax_ = s;
                        break;
                    }
                    case 74: {
                        java.lang.String s = input.readStringRequireUtf8();

                        heapCurrent_ = s;
                        break;
                    }
                    case 82: {
                        java.lang.String s = input.readStringRequireUtf8();

                        diskAvail_ = s;
                        break;
                    }
                    case 89: {

                        diskPercent_ = input.readDouble();
                        break;
                    }
                    case 98: {
                        java.lang.String s = input.readStringRequireUtf8();

                        group_ = s;
                        break;
                    }
                    case 106: {
                        java.lang.String s = input.readStringRequireUtf8();

                        tag_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_NodeInfo_descriptor;
    }

    public static com.rany.service.platform.meta.NodeInfo parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.rany.service.platform.meta.NodeInfo parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.rany.service.platform.meta.NodeInfo parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.rany.service.platform.meta.NodeInfo parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.rany.service.platform.meta.NodeInfo parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.rany.service.platform.meta.NodeInfo parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.rany.service.platform.meta.NodeInfo parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.rany.service.platform.meta.NodeInfo parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.rany.service.platform.meta.NodeInfo parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.rany.service.platform.meta.NodeInfo parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.rany.service.platform.meta.NodeInfo parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.rany.service.platform.meta.NodeInfo parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.rany.service.platform.meta.NodeInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.rany.service.platform.meta.NodeInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<NodeInfo> parser() {
        return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_NodeInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.rany.service.platform.meta.NodeInfo.class, com.rany.service.platform.meta.NodeInfo.Builder.class);
    }

    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
        return id_;
    }

    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
        }
    }

    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
    getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            name_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string ip_address = 3;</code>
     */
    public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            ipAddress_ = s;
            return s;
        }
    }

    /**
     * <code>string ip_address = 3;</code>
     */
    public com.google.protobuf.ByteString
    getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            ipAddress_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>bool is_master = 4;</code>
     */
    public boolean getIsMaster() {
        return isMaster_;
    }

    /**
     * <code>double cpu_percent = 5;</code>
     */
    public double getCpuPercent() {
        return cpuPercent_;
    }

    /**
     * <code>string ram_max = 6;</code>
     */
    public java.lang.String getRamMax() {
        java.lang.Object ref = ramMax_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            ramMax_ = s;
            return s;
        }
    }

    /**
     * <code>string ram_max = 6;</code>
     */
    public com.google.protobuf.ByteString
    getRamMaxBytes() {
        java.lang.Object ref = ramMax_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            ramMax_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string ram_current = 7;</code>
     */
    public java.lang.String getRamCurrent() {
        java.lang.Object ref = ramCurrent_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            ramCurrent_ = s;
            return s;
        }
    }

    /**
     * <code>string ram_current = 7;</code>
     */
    public com.google.protobuf.ByteString
    getRamCurrentBytes() {
        java.lang.Object ref = ramCurrent_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            ramCurrent_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string heap_max = 8;</code>
     */
    public java.lang.String getHeapMax() {
        java.lang.Object ref = heapMax_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            heapMax_ = s;
            return s;
        }
    }

    /**
     * <code>string heap_max = 8;</code>
     */
    public com.google.protobuf.ByteString
    getHeapMaxBytes() {
        java.lang.Object ref = heapMax_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            heapMax_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string heap_current = 9;</code>
     */
    public java.lang.String getHeapCurrent() {
        java.lang.Object ref = heapCurrent_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            heapCurrent_ = s;
            return s;
        }
    }

    /**
     * <code>string heap_current = 9;</code>
     */
    public com.google.protobuf.ByteString
    getHeapCurrentBytes() {
        java.lang.Object ref = heapCurrent_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            heapCurrent_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string disk_avail = 10;</code>
     */
    public java.lang.String getDiskAvail() {
        java.lang.Object ref = diskAvail_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            diskAvail_ = s;
            return s;
        }
    }

    /**
     * <code>string disk_avail = 10;</code>
     */
    public com.google.protobuf.ByteString
    getDiskAvailBytes() {
        java.lang.Object ref = diskAvail_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            diskAvail_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>double disk_percent = 11;</code>
     */
    public double getDiskPercent() {
        return diskPercent_;
    }

    /**
     * <code>string group = 12;</code>
     */
    public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            group_ = s;
            return s;
        }
    }

    /**
     * <code>string group = 12;</code>
     */
    public com.google.protobuf.ByteString
    getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            group_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string tag = 13;</code>
     */
    public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            tag_ = s;
            return s;
        }
    }

    /**
     * <code>string tag = 13;</code>
     */
    public com.google.protobuf.ByteString
    getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            tag_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (id_ != 0) {
            output.writeInt32(1, id_);
        }
        if (!getNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        if (!getIpAddressBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ipAddress_);
        }
        if (isMaster_ != false) {
            output.writeBool(4, isMaster_);
        }
        if (cpuPercent_ != 0D) {
            output.writeDouble(5, cpuPercent_);
        }
        if (!getRamMaxBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ramMax_);
        }
        if (!getRamCurrentBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ramCurrent_);
        }
        if (!getHeapMaxBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 8, heapMax_);
        }
        if (!getHeapCurrentBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 9, heapCurrent_);
        }
        if (!getDiskAvailBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 10, diskAvail_);
        }
        if (diskPercent_ != 0D) {
            output.writeDouble(11, diskPercent_);
        }
        if (!getGroupBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 12, group_);
        }
        if (!getTagBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 13, tag_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, id_);
        }
        if (!getNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        if (!getIpAddressBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ipAddress_);
        }
        if (isMaster_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(4, isMaster_);
        }
        if (cpuPercent_ != 0D) {
            size += com.google.protobuf.CodedOutputStream
                    .computeDoubleSize(5, cpuPercent_);
        }
        if (!getRamMaxBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ramMax_);
        }
        if (!getRamCurrentBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ramCurrent_);
        }
        if (!getHeapMaxBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, heapMax_);
        }
        if (!getHeapCurrentBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, heapCurrent_);
        }
        if (!getDiskAvailBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, diskAvail_);
        }
        if (diskPercent_ != 0D) {
            size += com.google.protobuf.CodedOutputStream
                    .computeDoubleSize(11, diskPercent_);
        }
        if (!getGroupBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, group_);
        }
        if (!getTagBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, tag_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.rany.service.platform.meta.NodeInfo)) {
            return super.equals(obj);
        }
        com.rany.service.platform.meta.NodeInfo other = (com.rany.service.platform.meta.NodeInfo) obj;

        boolean result = true;
        result = result && (getId()
                == other.getId());
        result = result && getName()
                .equals(other.getName());
        result = result && getIpAddress()
                .equals(other.getIpAddress());
        result = result && (getIsMaster()
                == other.getIsMaster());
        result = result && (
                java.lang.Double.doubleToLongBits(getCpuPercent())
                        == java.lang.Double.doubleToLongBits(
                        other.getCpuPercent()));
        result = result && getRamMax()
                .equals(other.getRamMax());
        result = result && getRamCurrent()
                .equals(other.getRamCurrent());
        result = result && getHeapMax()
                .equals(other.getHeapMax());
        result = result && getHeapCurrent()
                .equals(other.getHeapCurrent());
        result = result && getDiskAvail()
                .equals(other.getDiskAvail());
        result = result && (
                java.lang.Double.doubleToLongBits(getDiskPercent())
                        == java.lang.Double.doubleToLongBits(
                        other.getDiskPercent()));
        result = result && getGroup()
                .equals(other.getGroup());
        result = result && getTag()
                .equals(other.getTag());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + IP_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getIpAddress().hashCode();
        hash = (37 * hash) + IS_MASTER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getIsMaster());
        hash = (37 * hash) + CPU_PERCENT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                java.lang.Double.doubleToLongBits(getCpuPercent()));
        hash = (37 * hash) + RAM_MAX_FIELD_NUMBER;
        hash = (53 * hash) + getRamMax().hashCode();
        hash = (37 * hash) + RAM_CURRENT_FIELD_NUMBER;
        hash = (53 * hash) + getRamCurrent().hashCode();
        hash = (37 * hash) + HEAP_MAX_FIELD_NUMBER;
        hash = (53 * hash) + getHeapMax().hashCode();
        hash = (37 * hash) + HEAP_CURRENT_FIELD_NUMBER;
        hash = (53 * hash) + getHeapCurrent().hashCode();
        hash = (37 * hash) + DISK_AVAIL_FIELD_NUMBER;
        hash = (53 * hash) + getDiskAvail().hashCode();
        hash = (37 * hash) + DISK_PERCENT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                java.lang.Double.doubleToLongBits(getDiskPercent()));
        hash = (37 * hash) + GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getGroup().hashCode();
        hash = (37 * hash) + TAG_FIELD_NUMBER;
        hash = (53 * hash) + getTag().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeInfo> getParserForType() {
        return PARSER;
    }

    public com.rany.service.platform.meta.NodeInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code NodeInfo}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:NodeInfo)
            com.rany.service.platform.meta.NodeInfoOrBuilder {
        private int id_;
        private java.lang.Object name_ = "";
        private java.lang.Object ipAddress_ = "";
        private boolean isMaster_;
        private double cpuPercent_;
        private java.lang.Object ramMax_ = "";
        private java.lang.Object ramCurrent_ = "";
        private java.lang.Object heapMax_ = "";
        private java.lang.Object heapCurrent_ = "";
        private java.lang.Object diskAvail_ = "";
        private double diskPercent_;
        private java.lang.Object group_ = "";
        private java.lang.Object tag_ = "";

        // Construct using com.rany.service.platform.meta.NodeInfo.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_NodeInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_NodeInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.rany.service.platform.meta.NodeInfo.class, com.rany.service.platform.meta.NodeInfo.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            id_ = 0;

            name_ = "";

            ipAddress_ = "";

            isMaster_ = false;

            cpuPercent_ = 0D;

            ramMax_ = "";

            ramCurrent_ = "";

            heapMax_ = "";

            heapCurrent_ = "";

            diskAvail_ = "";

            diskPercent_ = 0D;

            group_ = "";

            tag_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.rany.service.platform.meta.SearchMiddlePlatformMetaService.internal_static_NodeInfo_descriptor;
        }

        public com.rany.service.platform.meta.NodeInfo getDefaultInstanceForType() {
            return com.rany.service.platform.meta.NodeInfo.getDefaultInstance();
        }

        public com.rany.service.platform.meta.NodeInfo build() {
            com.rany.service.platform.meta.NodeInfo result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.rany.service.platform.meta.NodeInfo buildPartial() {
            com.rany.service.platform.meta.NodeInfo result = new com.rany.service.platform.meta.NodeInfo(this);
            result.id_ = id_;
            result.name_ = name_;
            result.ipAddress_ = ipAddress_;
            result.isMaster_ = isMaster_;
            result.cpuPercent_ = cpuPercent_;
            result.ramMax_ = ramMax_;
            result.ramCurrent_ = ramCurrent_;
            result.heapMax_ = heapMax_;
            result.heapCurrent_ = heapCurrent_;
            result.diskAvail_ = diskAvail_;
            result.diskPercent_ = diskPercent_;
            result.group_ = group_;
            result.tag_ = tag_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.rany.service.platform.meta.NodeInfo) {
                return mergeFrom((com.rany.service.platform.meta.NodeInfo) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.rany.service.platform.meta.NodeInfo other) {
            if (other == com.rany.service.platform.meta.NodeInfo.getDefaultInstance()) return this;
            if (other.getId() != 0) {
                setId(other.getId());
            }
            if (!other.getName().isEmpty()) {
                name_ = other.name_;
                onChanged();
            }
            if (!other.getIpAddress().isEmpty()) {
                ipAddress_ = other.ipAddress_;
                onChanged();
            }
            if (other.getIsMaster() != false) {
                setIsMaster(other.getIsMaster());
            }
            if (other.getCpuPercent() != 0D) {
                setCpuPercent(other.getCpuPercent());
            }
            if (!other.getRamMax().isEmpty()) {
                ramMax_ = other.ramMax_;
                onChanged();
            }
            if (!other.getRamCurrent().isEmpty()) {
                ramCurrent_ = other.ramCurrent_;
                onChanged();
            }
            if (!other.getHeapMax().isEmpty()) {
                heapMax_ = other.heapMax_;
                onChanged();
            }
            if (!other.getHeapCurrent().isEmpty()) {
                heapCurrent_ = other.heapCurrent_;
                onChanged();
            }
            if (!other.getDiskAvail().isEmpty()) {
                diskAvail_ = other.diskAvail_;
                onChanged();
            }
            if (other.getDiskPercent() != 0D) {
                setDiskPercent(other.getDiskPercent());
            }
            if (!other.getGroup().isEmpty()) {
                group_ = other.group_;
                onChanged();
            }
            if (!other.getTag().isEmpty()) {
                tag_ = other.tag_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.rany.service.platform.meta.NodeInfo parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.rany.service.platform.meta.NodeInfo) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        /**
         * <code>int32 id = 1;</code>
         */
        public Builder setId(int value) {

            id_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 id = 1;</code>
         */
        public Builder clearId() {

            id_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string name = 2;</code>
         */
        public Builder setName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string name = 2;</code>
         */
        public Builder setNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         */
        public Builder clearName() {

            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
        }

        /**
         * <code>string ip_address = 3;</code>
         */
        public java.lang.String getIpAddress() {
            java.lang.Object ref = ipAddress_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ipAddress_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string ip_address = 3;</code>
         */
        public Builder setIpAddress(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            ipAddress_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string ip_address = 3;</code>
         */
        public com.google.protobuf.ByteString
        getIpAddressBytes() {
            java.lang.Object ref = ipAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ipAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string ip_address = 3;</code>
         */
        public Builder setIpAddressBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            ipAddress_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string ip_address = 3;</code>
         */
        public Builder clearIpAddress() {

            ipAddress_ = getDefaultInstance().getIpAddress();
            onChanged();
            return this;
        }

        /**
         * <code>bool is_master = 4;</code>
         */
        public boolean getIsMaster() {
            return isMaster_;
        }

        /**
         * <code>bool is_master = 4;</code>
         */
        public Builder setIsMaster(boolean value) {

            isMaster_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bool is_master = 4;</code>
         */
        public Builder clearIsMaster() {

            isMaster_ = false;
            onChanged();
            return this;
        }

        /**
         * <code>double cpu_percent = 5;</code>
         */
        public double getCpuPercent() {
            return cpuPercent_;
        }

        /**
         * <code>double cpu_percent = 5;</code>
         */
        public Builder setCpuPercent(double value) {

            cpuPercent_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>double cpu_percent = 5;</code>
         */
        public Builder clearCpuPercent() {

            cpuPercent_ = 0D;
            onChanged();
            return this;
        }

        /**
         * <code>string ram_max = 6;</code>
         */
        public java.lang.String getRamMax() {
            java.lang.Object ref = ramMax_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ramMax_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string ram_max = 6;</code>
         */
        public Builder setRamMax(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            ramMax_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string ram_max = 6;</code>
         */
        public com.google.protobuf.ByteString
        getRamMaxBytes() {
            java.lang.Object ref = ramMax_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ramMax_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string ram_max = 6;</code>
         */
        public Builder setRamMaxBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            ramMax_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string ram_max = 6;</code>
         */
        public Builder clearRamMax() {

            ramMax_ = getDefaultInstance().getRamMax();
            onChanged();
            return this;
        }

        /**
         * <code>string ram_current = 7;</code>
         */
        public java.lang.String getRamCurrent() {
            java.lang.Object ref = ramCurrent_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ramCurrent_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string ram_current = 7;</code>
         */
        public Builder setRamCurrent(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            ramCurrent_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string ram_current = 7;</code>
         */
        public com.google.protobuf.ByteString
        getRamCurrentBytes() {
            java.lang.Object ref = ramCurrent_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ramCurrent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string ram_current = 7;</code>
         */
        public Builder setRamCurrentBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            ramCurrent_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string ram_current = 7;</code>
         */
        public Builder clearRamCurrent() {

            ramCurrent_ = getDefaultInstance().getRamCurrent();
            onChanged();
            return this;
        }

        /**
         * <code>string heap_max = 8;</code>
         */
        public java.lang.String getHeapMax() {
            java.lang.Object ref = heapMax_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                heapMax_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string heap_max = 8;</code>
         */
        public Builder setHeapMax(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            heapMax_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string heap_max = 8;</code>
         */
        public com.google.protobuf.ByteString
        getHeapMaxBytes() {
            java.lang.Object ref = heapMax_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                heapMax_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string heap_max = 8;</code>
         */
        public Builder setHeapMaxBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            heapMax_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string heap_max = 8;</code>
         */
        public Builder clearHeapMax() {

            heapMax_ = getDefaultInstance().getHeapMax();
            onChanged();
            return this;
        }

        /**
         * <code>string heap_current = 9;</code>
         */
        public java.lang.String getHeapCurrent() {
            java.lang.Object ref = heapCurrent_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                heapCurrent_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string heap_current = 9;</code>
         */
        public Builder setHeapCurrent(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            heapCurrent_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string heap_current = 9;</code>
         */
        public com.google.protobuf.ByteString
        getHeapCurrentBytes() {
            java.lang.Object ref = heapCurrent_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                heapCurrent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string heap_current = 9;</code>
         */
        public Builder setHeapCurrentBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            heapCurrent_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string heap_current = 9;</code>
         */
        public Builder clearHeapCurrent() {

            heapCurrent_ = getDefaultInstance().getHeapCurrent();
            onChanged();
            return this;
        }

        /**
         * <code>string disk_avail = 10;</code>
         */
        public java.lang.String getDiskAvail() {
            java.lang.Object ref = diskAvail_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                diskAvail_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string disk_avail = 10;</code>
         */
        public Builder setDiskAvail(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            diskAvail_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string disk_avail = 10;</code>
         */
        public com.google.protobuf.ByteString
        getDiskAvailBytes() {
            java.lang.Object ref = diskAvail_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                diskAvail_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string disk_avail = 10;</code>
         */
        public Builder setDiskAvailBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            diskAvail_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string disk_avail = 10;</code>
         */
        public Builder clearDiskAvail() {

            diskAvail_ = getDefaultInstance().getDiskAvail();
            onChanged();
            return this;
        }

        /**
         * <code>double disk_percent = 11;</code>
         */
        public double getDiskPercent() {
            return diskPercent_;
        }

        /**
         * <code>double disk_percent = 11;</code>
         */
        public Builder setDiskPercent(double value) {

            diskPercent_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>double disk_percent = 11;</code>
         */
        public Builder clearDiskPercent() {

            diskPercent_ = 0D;
            onChanged();
            return this;
        }

        /**
         * <code>string group = 12;</code>
         */
        public java.lang.String getGroup() {
            java.lang.Object ref = group_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                group_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string group = 12;</code>
         */
        public Builder setGroup(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            group_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string group = 12;</code>
         */
        public com.google.protobuf.ByteString
        getGroupBytes() {
            java.lang.Object ref = group_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                group_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string group = 12;</code>
         */
        public Builder setGroupBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            group_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string group = 12;</code>
         */
        public Builder clearGroup() {

            group_ = getDefaultInstance().getGroup();
            onChanged();
            return this;
        }

        /**
         * <code>string tag = 13;</code>
         */
        public java.lang.String getTag() {
            java.lang.Object ref = tag_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                tag_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string tag = 13;</code>
         */
        public Builder setTag(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            tag_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string tag = 13;</code>
         */
        public com.google.protobuf.ByteString
        getTagBytes() {
            java.lang.Object ref = tag_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                tag_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string tag = 13;</code>
         */
        public Builder setTagBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            tag_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string tag = 13;</code>
         */
        public Builder clearTag() {

            tag_ = getDefaultInstance().getTag();
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:NodeInfo)
    }

}

