// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin/meta.proto

package com.rany.service.platform.meta;

public interface UpdateIndexTemplateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateIndexTemplateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string project = 2;</code>
   * @return The project.
   */
  java.lang.String getProject();
  /**
   * <code>string project = 2;</code>
   * @return The bytes for project.
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <pre>
   * Use StringValue to enable optional field;
   * </pre>
   *
   * <code>.google.protobuf.StringValue mapping = 3;</code>
   * @return Whether the mapping field is set.
   */
  boolean hasMapping();
  /**
   * <pre>
   * Use StringValue to enable optional field;
   * </pre>
   *
   * <code>.google.protobuf.StringValue mapping = 3;</code>
   * @return The mapping.
   */
  com.google.protobuf.StringValue getMapping();
  /**
   * <pre>
   * Use StringValue to enable optional field;
   * </pre>
   *
   * <code>.google.protobuf.StringValue mapping = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getMappingOrBuilder();

  /**
   * <pre>
   * Use StringValue to enable optional field;
   * </pre>
   *
   * <code>.google.protobuf.StringValue setting = 4;</code>
   * @return Whether the setting field is set.
   */
  boolean hasSetting();
  /**
   * <pre>
   * Use StringValue to enable optional field;
   * </pre>
   *
   * <code>.google.protobuf.StringValue setting = 4;</code>
   * @return The setting.
   */
  com.google.protobuf.StringValue getSetting();
  /**
   * <pre>
   * Use StringValue to enable optional field;
   * </pre>
   *
   * <code>.google.protobuf.StringValue setting = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getSettingOrBuilder();

  /**
   * <code>bool update_alias = 5;</code>
   * @return The updateAlias.
   */
  boolean getUpdateAlias();

  /**
   * <code>bool update_policy = 6;</code>
   * @return The updatePolicy.
   */
  boolean getUpdatePolicy();

  /**
   * <code>bool update_window = 7;</code>
   * @return The updateWindow.
   */
  boolean getUpdateWindow();

  /**
   * <code>repeated string aliases = 8;</code>
   * @return A list containing the aliases.
   */
  java.util.List<java.lang.String>
      getAliasesList();
  /**
   * <code>repeated string aliases = 8;</code>
   * @return The count of aliases.
   */
  int getAliasesCount();
  /**
   * <code>repeated string aliases = 8;</code>
   * @param index The index of the element to return.
   * @return The aliases at the given index.
   */
  java.lang.String getAliases(int index);
  /**
   * <code>repeated string aliases = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the aliases at the given index.
   */
  com.google.protobuf.ByteString
      getAliasesBytes(int index);

  /**
   * <code>.AutoIndexRollingPolicy auto_index_rolling_policy = 9;</code>
   * @return The enum numeric value on the wire for autoIndexRollingPolicy.
   */
  int getAutoIndexRollingPolicyValue();
  /**
   * <code>.AutoIndexRollingPolicy auto_index_rolling_policy = 9;</code>
   * @return The autoIndexRollingPolicy.
   */
  com.rany.service.platform.meta.AutoIndexRollingPolicy getAutoIndexRollingPolicy();

  /**
   * <code>int32 auto_index_rolling_window = 10;</code>
   * @return The autoIndexRollingWindow.
   */
  int getAutoIndexRollingWindow();
}
